name: goWeb

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH 
        uses: appleboy/ssh-action@v1.0.3 
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop:
          script: |
            cd /home/ubuntu
            mkdir -p goWebServer
            cd /home/ubuntu/goWebServer

            git init 2>&1
            git branch -M main 2>&1
            git remote add origin https://github.com/qkrwowoo/goWebServer.git 2>&1
            git pull origin main 2>&1

            sh -x build.sh goWeb 2>&1
            sh -x build.sh grpcWeb 2>&1
            
            cd ../
            ./goWeb/goWeb -f ./goWeb/goWeb.ini > ./output.log 2>&1 &
            ./grpcWeb/grpcWeb -f ./grpcWeb/grpcWeb.ini > ./output.log 2>&1 &